/* Generated By:JavaCC: Do not edit this line. JavaCCLexicalAnalyzerConstants.java */
package asint;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaCCLexicalAnalyzerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NATURAL = 1;
  /** RegularExpression Id. */
  int LETRA = 2;
  /** RegularExpression Id. */
  int NUM = 3;
  /** RegularExpression Id. */
  int BOOL = 4;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int NOT = 7;
  /** RegularExpression Id. */
  int TRUE = 8;
  /** RegularExpression Id. */
  int FALSE = 9;
  /** RegularExpression Id. */
  int ID = 10;
  /** RegularExpression Id. */
  int INT = 11;
  /** RegularExpression Id. */
  int DEC = 12;
  /** RegularExpression Id. */
  int EXE = 13;
  /** RegularExpression Id. */
  int PYC = 17;
  /** RegularExpression Id. */
  int OA = 18;
  /** RegularExpression Id. */
  int separator = 19;
  /** RegularExpression Id. */
  int RELACIONALES = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NATURAL>",
    "<LETRA>",
    "\"num\"",
    "\"bool\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"true\"",
    "\"false\"",
    "<ID>",
    "<INT>",
    "<DEC>",
    "<EXE>",
    "<token of kind 14>",
    "<token of kind 15>",
    "<token of kind 16>",
    "\";\"",
    "<OA>",
    "<separator>",
    "<RELACIONALES>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
  };

}
