
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu Apr 04 07:37:46 CEST 2019
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int AND = 19;
  public static final int LT = 13;
  public static final int NE = 16;
  public static final int PYC = 25;
  public static final int OR = 20;
  public static final int INT = 3;
  public static final int NOT = 21;
  public static final int PLS = 7;
  public static final int MNS = 8;
  public static final int GT = 11;
  public static final int ID = 2;
  public static final int LE = 14;
  public static final int NUM = 18;
  public static final int EOF = 0;
  public static final int PCE = 23;
  public static final int DIV = 10;
  public static final int EXE = 5;
  public static final int SEP = 24;
  public static final int PAO = 22;
  public static final int GE = 12;
  public static final int error = 1;
  public static final int EQ = 6;
  public static final int BOOL = 17;
  public static final int REAL = 4;
  public static final int MUL = 9;
  public static final int BE = 15;
}

